version: '3.1'

services:

  app:
    depends_on:
      - db
    build: 
      context: ./drupal/8/
    image: bgc/site
    env_file: .env
    ports:
      - 80:80
    volumes:
      - ./app:/app
    restart: always
    links:
      - db

  db:
    image: mariadb:10.3.6
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
     - db_data:/var/lib/mysql

volumes:
  db_data: